apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-4ykj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-4ykj
    app.kubernetes.io/part-of: nodejs-users
  name: simple-nodejs-app-4ykj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: simple-nodejs-app-4ykj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: simple-nodejs-app-4ykj
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-nqmj-tenant/nodejs-users/simple-nodejs-app-4ykj@sha256:455ef9484e06d0030375a69f0d95531a2c0abf78396363b10e6eb4c9a6e07484
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
